### PR TITLE
add codecov setting

### PR DESCRIPTION
**Pull request by Borda**
suggesting using some `codecov` configuration, so the path change has some thresholds

### CODE REVIEW

**Comment by Borda** [comment]
@mfeurer I would suggest using some `codecov` configuration, so the path change has some thresholds

**Comment by Borda** [comment]
it is not explicitly for `master`, the `auto` defines the target branch for PR

**Comment by mfeurer** [comment]
Oh, I meant where to merge this to, not the file itself.

**Comment by Borda** [comment]
Done

**Comment by mairieli** [comment]
Hi @Borda ! I've noticed that you changed the configuration of a bot in this PR. I am researching how to develop better GitHub bots. Would you be willing to participate in my research, answering a few questions?

**Pull request merged**
