### PR TITLE
closes #652

### LINKED ISSUE #652: Documentation update
Hey all,

When running Auto-Sklearn in parallel with `n_jobs` and providing a `True` flag for `delete_tmp_folder_after_terminate` and `delete_output_folder_after_terminate`, the directories are not deleted in the end. This is not reflected in the documentation, where for both parameters the following is written:
```
delete_tmp_folder_after_terminate: string, optional (True)
remove tmp_folder, when finished.......
```

### PR DESCRIPTION
**Pull request by gui-miotto**
Edited docstrings in estimators.py

### CODE REVIEW

**Comment by mfeurer** [comment]
Thanks, this is a helpful improvement of the docs. How about being a bit more specific and changing the last sentence to: "If not running in parallel and tmp_folder is None, then tmp_dir will always be deleted unless this argument is False."?

**Comment by mfeurer** [comment]
@arlindkadra @Motorrat would this description be less confusing?

**Comment by Motorrat** [comment]
One thing more to consider is that in this context n_jobs<>1,None it is not the only parallel mode. So maybe there’s a better way to refer to using n_jobs as opposed to the other parallel mechanisms or no parallelism at all. If it’s using joblib than maybe it should be explicitly referred to as such, for example?

**Comment by mfeurer** [comment]
> One thing more to consider is that in this context n_jobs<>1,None it is not the only parallel mode.
Good point.
>  If it’s using joblib than maybe it should be explicitly referred to as such, for example?
The interface is similar to joblib, but we're not using it at this point.

**Comment by gui-miotto** [comment]
> Thanks, this is a helpful improvement of the docs. How about being a bit more specific and changing the last sentence to: "If not running in parallel and tmp_folder is None, then tmp_dir will always be deleted unless this argument is False."?

Your are right, I just tested it and this last bit is not right. 
However, I just kind of used what was already there before: "_If tmp_folder is None tmp_dir will always be deleted_". I now wonder if this sentence was indeed correct.

**Comment by mfeurer** [comment]
Really, the tmp directory is deleted if `tmp_folder is None` even if the do not delete attribute is True?

**Comment by gui-miotto** [comment]
@mfeurer , I ran a test with the following parameters:

`       n_jobs=None,
        tmp_folder=**None**,
        output_folder=**None**,
        delete_tmp_folder_after_terminate=False,
        delete_output_folder_after_terminate=False`

The old docstring says: "_If tmp_folder is **None** tmp_dir will always be deleted_". So, if the docstring is correct, we would expect that the folders would be deleted, even though the delete_after_terminate parameters are set to False. Right?

But that is not the case. The folders stay there. So unless I'm missing something here, I think the old docstring was already inaccurate. Then maybe we could leave the new one as short as "_remove tmp_folder, when finished. Currently, tmp_folder won't be deleted if n_jobs is different than 1 or None"

Does all this make sense?

**Comment by gui-miotto** [comment]
Ok, I tested all the combinations between n_jobs, temp_folder and delete_tmp_folder_after_terminate. And here are the results

| n_jobs | tmp_folder | delete_tmp_folder_after_terminate | Deletes? |
|--------|------------|-------------------|---------|
| None   | None       | False             | False   |
| None   | None       | True              | True    |
| None   | specified  | False             | False   |
| None   | specified  | True              | True    |
| 2      | None       | False             | False   |
| 2      | None       | True              | False   |
| 2      | specified  | False             | False   |
| 2      | specified  | True              | False   |


As you can see, the behavior is actually independent of temp_folder.
So I suggest the following docstring:

> Removes tmp_folder when finished. However, if auto-sklearn is run in parallel, tmp_folder won't be deleted, even if delete_tmp_folder_after_terminate is True.

What do you think?

**Pull request closed without merging**
