### PR TITLE
Add black and isort to pre-commit hooks

### PR DESCRIPTION
**Pull request by isaac-chung**
Added lastest black and isort pre-commit hook versions in the yaml file.

### CODE REVIEW

**Comment by isaac-chung** [comment]
Address issue #1312

**Comment by eddiebergman** [comment]
Thanks for the work, it appears the tests itself fails due to `isort`. 

@mfeurer , do we want it to auto format things or just do a check? 

I'm also not sure how this auto-formatting works in relation to the actual code that is checked-in with the PR. @isaac-chung, do you know if this will format the code that would be merged or if it just formats the results and then discards the remainder?

**Comment by isaac-chung** [comment]
@eddiebergman afaik the code in this PR currently does not have the formatting from the new hooks. We are only seeing the formatting results in the test, but they are not being committed. What I can do is: run the new hooks in a separate commit, and push the formatted code here. Thoughts?

**Comment by eddiebergman** [comment]
No that's fine. We can also manually do that if we need.

For us:
* Do we want a github action that automatically performs black formatting and isorting to the code, such that all prs and commits are automatically blacked and isorted.
* Or... do want them purely as a check to say it is or isn't done.

@isaac-chung
black and isort have parameters when run in command line that simply performs a check and give output of the diff between formatted and non-formatted code, not actually formatting the code. Can this be performed through your code?

**Comment by isaac-chung** [comment]
@eddiebergman I see what you mean. To do what you requested (as part of the pre-commit hooks as develops hit `git commit`), the following would need to be added in `.git/hooks/pre-commit`:
```#!/usr/bin/env python
import sys
from isort.hooks import git_hook

sys.exit(git_hook(strict=False, modify=False, lazy=False))
```
This would display warnings, but allow the commit to happen anyway, and also to NOT fix the code, and to check only files added to your index.

We could also add isort and black as a Github Action, and the default would be to only check and show diff (example with isort: https://pycqa.github.io/isort/docs/configuration/github_action.html).

**Comment by eddiebergman** [comment]
@isaac-chung we will discuss this tomorrow during our meeting and get back to you then :)

**Comment by mfeurer** [comment]
My preferred workflow would be that this is executed on github and makes the build fail on an error. However, users should not commit such erroneous commits by using `pre-commit` on their own computer. In case we do not document this yet, we should add it to the contribution guide.

**Comment by eddiebergman** [comment]
@isaac-chung , we will black format and isort everything after the next release. This will be the first pull request merged after this next release, thank you for the contribution! :)

**Comment by isaac-chung** [comment]
Happy to help! :)

**Comment by eddiebergman** [comment]
Hi @isaac-chung,

I did a major update of our tooling in #1358 and incorporated this in, I will close this and attribute credit to you in that PR and our release notes. Thank you! :)

**Pull request closed without merging**
