### PR TITLE
Parallelize and chunk `AutoML.predict`

### LINKED ISSUE #239: Improvement: parallelize `AutoML.predict`
Prediction with an ensemble can take a long time depending on the number of models. A quick win would be to use a `multiprocessing.Pool.map` to replace this for loop in `AutoML.predict` (line 455-470):

```
all_predictions = []
for identifier in self.ensemble_.get_model_identifiers():
    model = self.models_[identifier]

    X_ = X.copy()
    if self._task in REGRESSION_TASKS:
        prediction = model.predict(X_)
    else:
        prediction = model.predict_proba(X_)

    if len(prediction.shape) < 1 or len(X_.shape) < 1 or \
            X_.shape[0] < 1 or prediction.shape[0] != X_.shape[0]:
        self._logger.warning("Prediction shape for model %s is %s "
                             "while X_.shape is %s" %
                             (model, str(prediction.shape),
                              str(X_.shape)))
    all_predictions.append(prediction)
```

### PR DESCRIPTION
**Pull request by lsorber**
Resolves #239.

### CODE REVIEW

**Comment by lsorber** [comment]
All right, finally got around to passing the `batch_size` to the actual model. Does it look ok to you now?

**Comment by mfeurer** [comment]
Looks good, thank you very much.

**Comment by mfeurer** [comment]
Now we only need to rebase on the development branch. I can do this, but if I do it, would you still be the author of the commits? Otherwise, would you like to do this?

**Comment by lsorber** [comment]
I rebased the PR onto `development`, and squashed the commits to clean up the history. Should be good to go now, although it looks like the pyrfr build failing is preventing Travis from running the tests. Let me know if you need anything else.

**Comment by mfeurer** [comment]
Thanks a lot @lsorber for your contribution to auto-sklearn! Further contributions are highly appreciated ;)

**Pull request merged**
