### PR TITLE
Remove warning "No models better than random - using Dummy Score!" fix #739

### LINKED ISSUE #739: [question!] No models better than random - using Dummy Score!
[WARNING] [2019-11-07 18:29:07,226:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!

what I should do to deal with this problem?

### PR DESCRIPTION
**Pull request by Rong-Inspur**
Remove warning "No models better than random - using Dummy Score!" since this error message seems to be very confusing. fix #739

### CODE REVIEW

**Comment by cturner500** [comment]
Would leave as-is.  This is useful to us when evaluating prediction power of features-- or lack thereof.

**Comment by mfeurer** [comment]
> Would leave as-is. This is useful to us when evaluating prediction power of features-- or lack thereof.

I'm not sure about this. This is mostly triggered when there are simply no other models besides the dummy model, which leads to a lot of confusion. Maybe the warning message should only be triggered if there are other models besides the dummy model? Maybe the info logging statement should be changed to reflect the current status of the ensemble building process?

**Comment by mfeurer** [comment]
Thanks a lot @Rong-Inspur for the contribution. I'll wait for further input from @cturner500 on his comment.

**Comment by cturner500** [comment]
Will defer to your judgement, @mfeurer .  Just wished to express that it's useful to know when the dummy score is invoked, esp. when working with imbalanced data where they dummy is quite competitive (i.e. assign all to one class)

**Comment by mfeurer** [comment]
Then triggering the warning only if there are other models besides the dummy model makes sense. @Rong-Inspur do you want to tackle this and update your pull request?

**Comment by Rong-Inspur** [comment]
> Then triggering the warning only if there are other models besides the dummy model makes sense. @Rong-Inspur do you want to tackle this and update your pull request?

Sure, I would like to work on this. Just want to clarify, when there are other models besides dummy model and those models are not better than random, trigger this warning. When there are no other models, no warning message?

**Comment by mfeurer** [comment]
> Sure, I would like to work on this.

:+1:

> when there are other models besides dummy model and those models are not better than random, trigger this warning. 

Correct

> When there are no other models, no warning message?

Correct

**Comment by Rong-Inspur** [comment]
@mfeurer Would like to know if the latest commit is good? Anything else I can help with this topic? Thanks!

**Comment by mfeurer** [comment]
Thanks @Rong-Inspur for the updated PR and the ping. Sorry for the slow answer from my side, I'm currently busy with the ICML deadline. The PR looks great. Do you think it would be informative for the user how many other models are potentially available, but have a dummy score (i.e. add `num_keys - 1` and `num_dummy` to the warning)?

**Comment by Rong-Inspur** [comment]
> Thanks @Rong-Inspur for the updated PR and the ping. Sorry for the slow answer from my side, I'm currently busy with the ICML deadline. The PR looks great. Do you think it would be informative for the user how many other models are potentially available, but have a dummy score (i.e. add `num_keys - 1` and `num_dummy` to the warning)?

Yeah it will definitely be more informative, but not sure if it is necessary since the warning message will go away after some time?

**Comment by mfeurer** [comment]
> Yeah it will definitely be more informative, but not sure if it is necessary since the warning message will go away after some time?

The idea would be to have it as a debug output as suggested by @cturner500. It would basically show you that the optimization is not progressing.

**Comment by Rong-Inspur** [comment]
> The idea would be to have it as a debug output as suggested by @cturner500. It would basically show you that the optimization is not progressing.

That make sense, I can help if decided to make this change.

**Comment by mfeurer** [comment]
That would be great @Rong-Inspur

**Comment by mfeurer** [comment]
Thanks a lot for your help @Rong-Inspur and for your input @cturner500

**Pull request merged**
