### PR TITLE
As discussed in the issues

### PR DESCRIPTION
**Pull request by Motorrat**
I have added comments and moved the dataset load outside of the loop. Also corrected a typo. Hope this helps.

### CODE REVIEW

**Comment by mfeurer** [comment]
Thank you for the PR. This all makes sense, but I wonder how the `spawn_classifier` method gets the data?

**Comment by Motorrat** [comment]
In this case when defined outside of the loop it becomes a global variable and is visible inside all methods. I have used this to look up the right verbiage http://python-textbok.readthedocs.io/en/latest/Variables_and_Scope.html

**Comment by mfeurer** [comment]
Ah, thank you for that link. Could you please do me a favour and make this PR point to the development branch? I will then merge it.

**Comment by mfeurer** [comment]
I just merged this PR into the development branch.

**Pull request closed without merging**
