### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by timothyjlaurent**
I tried install this on 2 different linux machines and each one necessitated that cython was installed first.

### CODE REVIEW

**Comment by mfeurer** [comment]
What version of pip do you use? I'm right now not even sure whether one has to install the requirements manually because I just tried `pip install auto-sklearn` and it worked (using pip 8.1.2).

**Comment by timothyjlaurent** [comment]
OK so I started up a fresh up a fresh ubuntu container, and installed pip:

```
docker run --rm -it ubuntu bash
apt-get update
apt-get install pip  # this installs pip 8.1.1
```

^ this fails -- no numpy

upgrade pip:

```
pip install --upgrade pip 
pip install auto-sklearn
```

^ Still no numpy

ok lets try the requirements:

```
pip install -r https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt
```

^^ still no module named numpy

hmmm maybe the `requirements.txt` isn't required

```
pip install numpy
pip install auto-sklearn
```

^^ no `Cython`

```
pip install cython
pip install auto-sklearn
```

^ no module named `six`

```
pip install -r https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt
```

^ no module named `six` again

```
pip install six
pip install auto-sklearn
```

^This **works**

Starting over fresh:

```
docker run --rm -it ubuntu bash
apt-get update
apt-get install -yq python-pip
pip install numpy six cython
pip install auto-sklearn
```

So from this, on a fresh ubuntu, the only requirements to install are:

1. `pip`
2. `numpy six cython`
3. `auto-sklearn`

^ BTW this flow also works for install on OSX

I will update the PR to reflect this.

**Comment by mfeurer** [comment]
Interesting, I've got no idea why this is the case. What do you think of this more general solution?

    cat requirements.txt | xargs -n 1 -L 1 pip install

Would this work on OSX as well?

**Comment by mfeurer** [comment]
Related to #108

**Comment by timothyjlaurent** [comment]
If `requirements.txt` looks like:

```
six
numpy
cython
```

you should be able to just

```
> pip install -r requirements.txt
> pip install auto-sklearn
```

And that works on OSX too.

**Comment by mfeurer** [comment]
Thank you for your suggestions. I considered them for re-sorting the requirements file in ed50ed1810d8359a54c8428cadd198820de9b5ed which I merged into the development branch. Would this PR still help? If yes, would you mind pointing it to the development branch?

**Comment by donaldbraman** [comment]
@timothyjlaurent, would you be willing to contribute a Dockerfile to a docker-stacks repository that @mfeurer creates?

**Comment by timothyjlaurent** [comment]
@donaldbraman, I'd be happy to contribute a docker file to the @mfeurer's docker stacks repo.

**Pull request closed without merging**
