### PR TITLE
Fix max_features for forest classifiers, as per #358

### PR DESCRIPTION
**Pull request by engelen**
This implements the changes discussed in #358. The unit tests fail as a result of it, as the default configuration has changed (to `sqrt(m)`), which means the default results in [test_random_forest.py](https://github.com/automl/auto-sklearn/blob/master/test/test_pipeline/components/classification/test_random_forest.py) and [test_extra_trees.py](https://github.com/automl/auto-sklearn/blob/master/test/test_pipeline/components/classification/test_extra_trees.py) should be updated to reflect that. I couldn't find a pipeline for generating these results; is there one @mfeurer ?

### CODE REVIEW

**Comment by mfeurer** [comment]
This looks great!

I usually start these unit tests in [pycharm](https://www.jetbrains.com/pycharm/) and copy-paste those numbers into the test file. You could also use `nosetests` from the command line like this:

    nose test/test_pipeline/components/classification/test_extra_trees.py

This might also work:

    nose test.test_pipeline.components.classification.test_extra_trees

and a single specific test:

    nose test.test_pipeline.components.classification.test_extra_trees:ExtraTreesComponentTest.test_default_iris

For the meta-learning tests to pass you need to adapt `test/test_metalearning/pyMetaLearn/test_meta_base_data/configurations.csv` and make sure that the hyperparameter settings in there are within the updated ranges.

**Comment by engelen** [comment]
Thanks for the information! 5bf6a3a includes the new default performance results for RF and ET. For the meta-learning procedure: what do the numbers in there signify?

**Comment by mfeurer** [comment]
These are the initial configurations which can be used via meta-learning. They're loaded and parsed at the startup of Auto-sklearn. As the ranges for the parameter `max_features` changed, a lot of these configurations have become invalid. Making the columns of `classifier:random_forest:max_features` and `classifier:extra_trees:max_features` lie between 0 and 1 should make the failing unit tests pass (you can check locally as with the other tests).

**Comment by engelen** [comment]
Ah, okay, that makes sense. Is there any reason to not change them all to a fixed value like, say, 0.5?

**Comment by mfeurer** [comment]
Nope, there's no reason not to do that.

**Comment by mfeurer** [comment]
Looks great, thanks a lot! Not sure what's wrong with the unit test, but their failure seems unrelated.

**Comment by engelen** [comment]
Not a problem! Sorry for taking so long; theses take time :-).

**Pull request merged**
