### PR TITLE
Fix typo and link formatting in FAQ

### PR DESCRIPTION
**Pull request by PGijsbers**
As per title.

### CODE REVIEW

**Review by eddiebergman — APPROVED** [review]

**Comment by eddiebergman** [comment]
Looks good, thank you very much for the doc fixes, very much appreciated!

**Comment by eddiebergman** [comment]
Hmm they're failing to build but it appears to be unrelated, seperate issue that we need to address.

@mfeurer Am I okay to merge simple doc changes such as this?

**Comment by mfeurer** [comment]
Yes, they appear unrelated, you can go ahead an squash merge this thingy.

**Comment by PGijsbers** [comment]
I'm confused, looks like Matthias suggested a merge instead of closing without?

**Comment by eddiebergman** [comment]
Was there more fixes? I can go ahead and reopen the branch. That was my bad as I assumed that was it for the PR

**Comment by PGijsbers** [comment]
No there wouldn't be any more commits to this branch, because from my understanding Matthias was fine with merging this as-is (and I assume tackle the doc build issues in a separate PR by whomever takes that up).

**Comment by eddiebergman** [comment]
Ahh okay, yes I documented it in (#1196). We're trying to get some more important long term plans for auto-sklearn done at the moment but we'll get back to it soon!

**Comment by mfeurer** [comment]
Sorry, my comment was a bit too brief. I'm fine with you merging this, @eddiebergman. And I think the test failures are unrelated to these changes.

**Comment by eddiebergman** [comment]
@PGijsbers @mfeurer I realise the confusion now ... I thought I hit merge but apparently not -_-

**Comment by PGijsbers** [comment]
Don't worry about it, glad it's resolved!

**Pull request merged**
