### PR TITLE
fix installation from pip

### PR DESCRIPTION
**Pull request by Borda**
updating setup.py for installation from PyPi, see #610

### CODE REVIEW

**Comment by Borda** [comment]
@mfeurer tthe compilation are there now extra and they are not needed if you do not ant them
* '-O3'  is code optimization flag, it turns on all optimizations specified by -O2 and also turns on the extra optimization flags - see https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
* '-ffast-math' allows optimizations that do not preserve strict IEEE compliance, see https://stackoverflow.com/questions/7420665/what-does-gccs-ffast-math-actually-do
* '-fopenmp'  links the OpenMP if it is used - https://en.wikipedia.org/wiki/OpenMP

**Comment by Borda** [comment]
@mfeurer I can do it but probably in another PR as it would mean rewrite the Travis or add another CI wchich would be just for Ubuntu like [CircleCI](https://circleci.com/) or [Shippable](https://www.shippable.com)

**Comment by mfeurer** [comment]
Thanks for the explanation. As the code which is compiled is typically not used by any Auto-sklearn user (unless data from the 1st and 2nd automl competition is read) I would prefer to not apply any optimization to this piece of code and keep it is at is. Could you please remove these compile flags?

And yes, it would make sense to have the ubuntu test in a second pull request.

**Comment by Borda** [comment]
no problem, I have added come tags according the topic

**Comment by Borda** [comment]
@mfeurer and do you agree about another CI for ubuntu or heavy refactoring of Travis?

**Comment by mfeurer** [comment]
Actually, I would prefer to stick with only travis to keep maintenance low, especially as we recently moved from circle-ci to travis-ci for documentation building. I suggest to do installation like in scikit-learn, where there is a [specific installation script](https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/travis/install.sh), and switch in there between installing via anaconda or with the ubuntu packages. What do you think about that?

**Comment by Borda** [comment]
@mfeurer how many reviews are needed? :)

**Comment by mfeurer** [comment]
One, I just wanted travis-ci to finish.

**Comment by Borda** [comment]
I am sorry, I just noticed that there is an unused function in setup... :(

**Pull request merged**
