### PR TITLE
start updating scikit-learn

### PR DESCRIPTION
**Pull request by auvipy**
to address https://github.com/automl/auto-sklearn/issues/1371

### CODE REVIEW

**Comment by auvipy** [comment]
I will check the codes & try to make them pass gradually

**Comment by eddiebergman** [comment]
That's fine, I just enabled checks so they can run regularly, no rush :)

**Comment by eddiebergman** [comment]
Hi @auvipy,

Do you plan to continue this? If not, I would rather close this and deal with it when we're ready.

Best,
Eddie

**Comment by auvipy** [comment]
I will start working on this from next monday :D just ping me that day

**Comment by eddiebergman** [comment]
No problem, just checking that there's still a future plan to work on this :)

**Review by auvipy — COMMENTED** [review]
my understanding is, this change is still a relevant one! if yes I can resume work on this

**Pull request closed without merging**
